version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    command: bash -lc "alembic upgrade head && sanic main.app --host=0.0.0.0 --port=8000 --dev"
volumes:
  pgdata:
